import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BubbleChat } from "./bubbleChat";
import { MessageCircle, NotepadText } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        
        {/* navbar */}
        <div className="fixed bottom-0 h-20 bg-tertiary w-screen flex justify-around">
          <div className="flex flex-col gap-y-1 items-center justify-center">
            <MessageCircle size={28} />
            <p className="font-semibold text-base">Chat</p>
          </div>

          <div className="flex flex-col gap-y-1 items-center justify-center">
            <NotepadText size={28} />
            <p className="font-semibold text-base">History</p>
          </div>
        </div>
      </body>

      {/* navbar */}
    </html>
  );
}
